query Post(
  $limit:Int
  $posttype:String
  ){
  posts(
    post_type: [$posttype], 
    limit: $limit
    )
    {
      id
      post_name
      post_title
      post_date
      post_status
    }
}